language: python
python:
  - "3.7"
cache: pip
sudo: false
install:
  - travis_retry ./test/install.sh
script:
  - ./test/test.sh
env:
  - NEURAL_SP_PYTHON_VERSION=3.7 PYTORCH_VERSION=1.0.0 CC=gcc-7 CXX=g++-7
